title: "Stefano Racioppi: About Me"
description: >- 
  Personal website of Stefano Racioppi.
  A hub for research, projects, and writings.

theme: jekyll-theme-minimal

markdown: kramdown
highlighter: rouge


author:
  name: Stefano Racioppi
  email: sraciopp@buffalo.edu
  alt_email: stefanorac@hotmai.it

plugins:
  - jekyll-feed
  - jekyll-seo-tag
